[package]
name = "nestalgic_mos6502"
version = "0.1.0"
authors = ["Jake Woods <jake@jakewoods.net>"]
edition = "2021"

[dependencies]
thiserror = "1.0"

[dev-dependencies]
nestalgic_rom = { path = "../nestalgic_rom" }
